config/routes.rb
Rails.application.routes.draw do
  resources :category_rules, except: [:index]
  resources :categories, except: [:index]
  resources :bank_accounts, except: [:index] do
    resources :bank_transactions
    post 'imports/create'
  end
  resources :uncategorized_bank_transactions, only: [:index]

  get 'dashboard', to: 'dashboard#index'

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  get 'features', to: 'pages#features'
  get 'howto', to: 'pages#howto'

  devise_for :users
end

app/controllers/bank_transactions_controller.rb
class BankTransactionsController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!
  before_action :set_bank_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authorize_bank_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @bank_account = policy_scope(BankAccount)
                      .includes(:bank_transactions)
                      .find(params[:bank_account_id])
  end

  def show
  end

  def new
    @bank_transaction = policy_scope(BankAccount)
                        .find(params[:bank_account_id])
                        .bank_transactions.build
  end

  def edit
  end

  def create
    @bank_transaction = policy_scope(BankAccount)
                          .find(params[:bank_account_id])
                          .bank_transactions
                          .build(bank_transaction_params)

    if @bank_transaction.save
       redirect_to bank_account_bank_transactions_path(@bank_transaction.bank_account, @bank_transaction), notice: 'Bank transaction was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bank_transaction.update(bank_transaction_params)
      redirect_back fallback_location: bank_account_bank_transactions_path(@bank_transaction.bank_account, @bank_transaction), notice: 'Bank transaction was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bank_transaction.destroy
    redirect_to bank_account_bank_transactions_path(@bank_transaction.bank_account), notice: 'Bank transaction was successfully destroyed.'
  end

  private
    def set_bank_transaction
      @bank_transaction = BankTransaction.find(params[:id])
    end

    def authorize_bank_transaction
      authorize @bank_transaction
    end

    def bank_transaction_params
      params.require(:bank_transaction).permit(
        :date,
        :amount,
        :status,
        :number,
        :payee,
        :memo,
        :address,
        :bank_category,
        :category_id)
    end
end

app/helpers/bank_transactions_helper.rb
module BankTransactionsHelper
end

app/views/bank_transactions/_form.html.erb
<%= form_with(model: [bank_transaction.bank_account, bank_transaction], local: true) do |form| %>
  <% if bank_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_transaction.errors.count, "error") %> prohibited this bank_transaction from being saved:</h2>
      <ul>
        <% bank_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>
  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>
  <div class="field">
    <%= form.label :payee %>
    <%= form.text_field :payee %>
  </div>
  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div class="field">
    <%= form.label :bank_category %>
    <%= form.text_field :bank_category %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bank_transactions/edit.html.erb
<h1>Editing Bank Transaction</h1>
<%= render 'form', bank_transaction: @bank_transaction %>
<%= link_to 'Show', bank_account_bank_transaction_path(@bank_transaction.bank_account, @bank_transaction) %> |
<%= link_to 'Back', bank_account_bank_transactions_path(@bank_transaction.bank_account) %>
<td><%= link_to 'Destroy', bank_account_bank_transaction_path(@bank_transaction.bank_account), method: :delete, data: { confirm: 'Are you sure?' }, id: 'delete_bank_transaction' %></td>

app/views/bank_transactions/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Account Transactions</h1>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Number</th>
      <th>Payee</th>
      <th>Memo</th>
      <th>Address</th>
      <th>Bank Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bank_account.bank_transactions.each do |bank_transaction| %>
      <tr>
        <td><%= bank_transaction.date %></td>
        <td><%= bank_transaction.amount %></td>
        <td><%= bank_transaction.status %></td>
        <td><%= bank_transaction.number %></td>
        <td><%= bank_transaction.payee %></td>
        <td><%= bank_transaction.memo %></td>
        <td><%= bank_transaction.address %></td>
        <td><%= bank_transaction.bank_category %></td>
        <td><%#= link_to 'Show', bank_account_bank_transaction_path(bank_transaction) %></td>
        <td><%#= link_to 'Edit', edit_bank_transaction_path(bank_transaction) %></td>
        <td><%#= link_to 'Destroy', bank_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Bank Transaction', new_bank_account_bank_transaction_path(@bank_account), id: 'new_bank_transaction'%>

app/views/bank_transactions/new.html.erb
<h1>New Bank Transaction</h1>
<%= render 'form', bank_transaction: @bank_transaction %>
<%= link_to 'Back', bank_account_bank_transactions_path(@bank_transaction.bank_account) %>

app/views/bank_transactions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Date:</strong>
  <%= @bank_transaction.date %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @bank_transaction.amount %>
</p>
<p>
  <strong>Status:</strong>
  <%= @bank_transaction.status %>
</p>
<p>
  <strong>Number:</strong>
  <%= @bank_transaction.number %>
</p>
<p>
  <strong>Payee:</strong>
  <%= @bank_transaction.payee %>
</p>
<p>
  <strong>Memo:</strong>
  <%= @bank_transaction.memo %>
</p>
<p>
  <strong>Address:</strong>
  <%= @bank_transaction.address %>
</p>
<p>
  <strong>Bank Category:</strong>
  <%= @bank_transaction.bank_category %>
</p>
<%= link_to 'Edit', edit_bank_account_bank_transaction_path(@bank_transaction.bank_account, @bank_transaction), id: 'edit_bank_transaction' %> |
<%= link_to 'Back', bank_account_bank_transactions_path(@bank_transaction.bank_account) %>