config/routes.rb
Rails.application.routes.draw do
  resources :category_rules, except: [:index]
  resources :categories, except: [:index]
  resources :bank_accounts, except: [:index] do
    resources :bank_transactions
    post 'imports/create'
  end
  resources :uncategorized_bank_transactions, only: [:index]

  get 'dashboard', to: 'dashboard#index'

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  get 'features', to: 'pages#features'
  get 'howto', to: 'pages#howto'

  devise_for :users
end

app/views/shared/_dashboard_category_rules.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <th>Status</th>
      <th>Payee</th>
      <th>Memo</th>
      <th>Address</th>
      <th>Bank Category</th>
      <th></th>
    </thead>
    <tbody>
      <% category_rules.each do |category_rule| %>
        <tr>
          <td><%= category_rule.match_status%></td>
          <td><%= category_rule.match_payee%></td>
          <td><%= category_rule.match_memo%></td>
          <td><%= category_rule.match_address%></td>
          <td><%= category_rule.match_bank_category%></td>
          <td>
            <%= link_to edit_category_rule_path(category_rule), id: "edit_category_rule#{category_rule.id}" do %>
              <span class='category-rule-glyph' data-feather='edit'></span>
            <% end %>
            <%= link_to category_rule_path(category_rule),
                  id: "delete_category_rule#{category_rule.id}",
                  method: :delete,
                  data: { confirm: 'Are you sure you want to delete this category rule?'} do %>
              <span class='category-rule-glyph' data-feather='trash'></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_dashboard_chart_category_breakdown.html.erb
<h2>Category Breakdown</h2>
<%= column_chart_helper @bank_transactions_by_category %>
<hr>

app/views/shared/_dashboard_chart_incoming_outgoing.html.erb
<h2>Incoming vs Outgoing</h2>
<%= donut_chart_helper @bank_transaction_directionals %>
<hr>

app/views/shared/_dashboard_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark p-0">
  <%= link_to dashboard_path, class: "navbar-brand col-sm-3 col-md-2" do %>
    <%= nav_bar_brand %>
  <% end %>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Getting started', howto_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto pr-2">
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_dashboard_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark p-0">
  <%= link_to dashboard_path, class: "navbar-brand col-sm-3 col-md-2" do %>
    <%= nav_bar_brand %>
  <% end %>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Getting started', howto_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto pr-2">
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_dashboard_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Accounts</span>
      <%= link_to new_bank_account_path, class: 'd-flex align-items-center text-muted', id: 'new_bank_account' do %>
        <span data-feather="plus-circle"></span>
      <% end %>
    </h6>
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path, class: "nav-link #{active? dashboard_path}" do %>
          <span data-feather="book-open"></span>
          Overview
        <% end %>
      </li>
      <% get_sidebar_bank_accounts.each do |ba| %>
        <li class="nav-item">
          <%= link_to bank_account_path(ba), class: "nav-link #{active? bank_account_path(ba)}" do %>
            <span data-feather="bar-chart-2"></span>
            <%= ba.name %>
          <% end %>
        </li>
      <% end %>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Categories</span>
      <%= link_to new_category_path, class: 'd-flex align-items-center text-muted', id: 'new_category' do %>
        <span data-feather="plus-circle"></span>
      <% end %>
    </h6>
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "Uncategorized", uncategorized_bank_transactions_path, class: "nav-link" %>
      </li>
      <% get_sidebar_categories.each do |c| %>
        <li class="nav-item">
          <%= link_to category_path(c), class: "nav-link #{active? category_path(c)}" do %>
            <span data-feather="layers"></span>
            <%= c.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_dashboard_titlebar.html.erb
<div class="d-flex flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1>
    <%= name %>
    <small class='category-edit'>
      (<%= link_to 'Edit', edit_path, id: edit_id %>)
    </small>
  </h1>
  <div class="ml-auto btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <%= link_to [record, timespan: @timespan, page: @page+1], class: "btn btn-sm btn-outline-secondary #{@page >= @max_page ? 'disabled' : ''}" do %>
        <span data-feather="skip-back"></span>
        Prev
      <% end %>
      <%= link_to [record, timespan: @timespan, page: @page-1], class: "btn btn-sm btn-outline-secondary #{@page < 1 ? 'disabled' : ''}" do %>
        Next
        <span data-feather="skip-forward"></span>
      <% end %>
    </div>
    <div class="dropdown mr-5">
      <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
        <span data-feather="calendar"></span>
        <%= timespan_text @timespan %>
      </button>
      <div class="dropdown-menu">
        <% get_nonactive_timespans(@timespan).each do |timespan| %>
          <%= link_to [record, timespan: timespan], class: 'btn btn-sm btn-block btn-outline-secondary' do %>
            <span data-feather="calendar"></span>
            <%= timespan_text timespan %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard_transactions.html.erb
<!-- TODO: pagination -->
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <% if show_category %>
        <th>Category</th>
      <% end %>
      <th>Date</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Payee</th>
      <th>Memo</th>
      <th>Address</th>
      <th>Bank Category</th>
    </thead>
    <tbody>
      <% @bank_transactions.each do |trans| %>
        <tr>
          <% if show_category %>
            <% select_categories ||= nil %>
            <% if select_categories.present? %>
              <td>
              <%= form_with model: [trans.bank_account, trans] do |f| %>
                <%= f.collection_select(:category_id, select_categories, :id, :name, include_blank: '') %>
                <%= f.submit "Update"%>
              <% end %>
              </td>
            <% else %>
              <td><%= category_link_helper trans.category %></td>
            <% end %>
          <% end %>
          <td><%= trans.date %></td>
          <td><%= trans.status %></td>
          <td class="<%= currency_color_class trans.amount %>">
            <%= number_to_currency(trans.amount) %>
          </td>
          <td><%= trans.payee %></td>
          <td><%= trans.memo %></td>
          <td><%= trans.address %></td>
          <td><%= trans.bank_category %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= flash_type_to_class(type) %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_home_footer.html.erb
<footer class="container py-5">
  <hr>
  <div class="row">
    <div class="col-md-4">
      <div>
        <%= footer_brand %>
        <small class="mb-3 text-muted">&copy; 2018</small>
      </div>
    </div>
    <div class="col-md-8">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li>
          <%= link_to 'How it works', howto_path, class: "text-muted" %>
        </li>
        <li>
          <%= link_to 'Features', features_path, class: "text-muted" %>
        </li>
        <li>
          <%= link_to 'Pricing', pricing_path, class: "text-muted" %>
        </li>
        <li>
          <%= link_to 'About', about_path, class: 'text-muted' %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_home_nav_links.html.erb
<nav class="site-header sticky-top py-1">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <%= link_to root_path, class: 'py-2' do %>
      <%= nav_bar_brand %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'Dashboard', dashboard_path, class: 'py-2 d-none d-md-inline-block' %>
    <% end %>
    <%= link_to 'How it works', howto_path, class: "py-2 d-none d-md-inline-block #{active? howto_path}" %>
    <%= link_to 'Features', features_path, class: "py-2 d-none d-md-inline-block #{active? features_path}" %>
    <%= link_to 'Pricing', pricing_path, class: "py-2 d-none d-md-inline-block #{active? pricing_path}" %>
    <%= link_to 'About', about_path, class: "py-2 d-none d-md-inline-block #{active? about_path}" %>
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'py-2 d-none d-md-inline-block logout' %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "py-2 d-none d-md-inline-block register #{active? new_user_registration_path}" %>
      <%= link_to 'Login', new_user_session_path, class: "py-2 d-none d-md-inline-block login #{active? new_user_session_path}" %>
    <% end %>
  </div>
</nav>