config/routes.rb
Rails.application.routes.draw do
  resources :category_rules, except: [:index]
  resources :categories, except: [:index]
  resources :bank_accounts, except: [:index] do
    resources :bank_transactions
    post 'imports/create'
  end
  resources :uncategorized_bank_transactions, only: [:index]

  get 'dashboard', to: 'dashboard#index'

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  get 'features', to: 'pages#features'
  get 'howto', to: 'pages#howto'

  devise_for :users
end

app/views/pages/about.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 bg-light">
  <div class="col-md-8 p-lg-5 mx-auto my-5">
    <div class="card">
      <div class="card-body about-container">
        <h1 class="card-title text-center">About</h1>
        <div class="card-text">
          <p>Budget-a-tron is produced by <a href='http://www.jmiles.me'>Jonathan Miles</a>.</p>
          <p>The site was created both as an addition to my personal portfolio and as a tool to manage my own finances.</p>
          <p>The code is freely available from <a href='https://github.com/MC-Squared/Budget-a-tron.com'>Github</a> under a GPLv3 license.</p>
          <p>If you would like to contribute to the development and continued hosting of this site please see the <%= link_to 'Pricing', pricing_path %> page.</p>
        </div>
        <div class='mt-5 card-text'>
          <small>The <i>Budget-a-tron</i> logo and assorted page images have been provided by Flaticon:</small><br>
          <small>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> are licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></small><br>
          <small>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> are licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/features.html.erb
<div class="container marketing">
  <div class="row">
    <div class="col-md-5">
      <h2>Track your net worth</h2>
      <p class="lead">See your combined cash assets and how they are spread across your accounts.</p>
      <p class="lead">Mouse over the chart to see datapoints for individual days.</p>
    </div>
    <div class="col-md-7">
      <%= area_chart_helper @demo_net_worth_data %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-5 order-md-2">
      <h2>Monitor your cashflow</h2>
      <p class="lead">Easily see how much money you are bringing in compared with how much you are spending.</p>
    </div>
    <div class="col-md-7 order-md-1">
      <%= donut_chart_helper @demo_cashflow_data %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-7">
      <h2>Categorise your cash</h2>
      <p class="lead">See where your money is going by categorising your transactions.</p>
    </div>
    <div class="col-md-5">
      <%= column_chart_helper @demo_category_data %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <%= image_tag 'logo.svg', class: "watermark-logo float-left " %>
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-5 font-weight-normal">Budget-a-tron</h1>
    <p class="lead font-weight-normal">Bank statements go in.<br>
      Knowledge comes out.</p>
    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-secondary' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>
<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Bank Statements</h2>
      <p class="lead">Import as QIF</p>
    </div>
    <div>
      <%= image_tag 'bank_statements.svg', class: 'home-workflow-img' %>
      <div class='chevron float-right'>&rang;</div>
    </div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Budget-a-tron</h2>
      <p class="lead">Works its magic</p>
    </div>
    <%= image_tag 'logo.svg', class: 'home-workflow-img' %>
    <div class='chevron float-right logo-color'>&rang;</div>
  </div>
  <div class="bg-primary mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Enlightenment</h2>
      <p class="lead">See your finances</p>
    </div>
    <%= image_tag 'knowledge.svg', class: 'home-workflow-img' %>
  </div>
</div>

app/views/pages/howto.html.erb
<div class="col-md-8 p-lg-5 mx-auto my-5">
  <h2 class="text-center">Getting started checklist</h2>
  <ul class="list-group">
    <li class="list-group-item">
      <%= howto_list_item(1, 'Create', 'account', new_user_registration_path, user_signed_in?) %>
    </li>
    <li class="list-group-item">
      <%= howto_list_resource(2, 'Create', :bank_accounts, new_bank_account_path) %>
    </li>
    <li class="list-group-item">
      <%= howto_list_resource(3, 'Create', :categories, new_category_path) %>
    </li>
    <li class="list-group-item">
      <%= howto_list_resource(4, 'Create', :category_rules, new_category_rule_path) %>
    </li>
    <li class="list-group-item">
      <% if user_signed_in? && current_user.bank_accounts.count > 0 %>
        <%= howto_list_resource(5, 'Upload', :bank_transactions, bank_account_path(current_user.bank_accounts.first, anchor: 'transactions')) %>
      <% else %>
        5. Upload bank transactions
      <% end %>
      <small>Currently only QIF format is supported</small>
    </li>
    <li class="list-group-item">6. Done!</li>
  </ul>
</div>

app/views/pages/pricing.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead"><i>Budget-a-tron</i> is 100% free and open source.<br>
    To help continue hosting and development please consider donating through
    one of the links below.
  </p>
</div>
<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>1 user included</li>
          <li>Unlimited everything</li>
          <li>&nbsp;</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">One-off donation</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$? <small class="text-muted"></small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Feel-good factor</li>
          <li>Buy the developer a coffee</li>
          <li>&nbsp;</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
    <div class="card mb-4 box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Recurring donation</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$? <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Extra feel-good factor</li>
          <li>Help support development</li>
          <li>My undying gratitude</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
  </div>
</div>