config/routes.rb
Rails.application.routes.draw do
  resources :category_rules, except: [:index]
  resources :categories, except: [:index]
  resources :bank_accounts, except: [:index] do
    resources :bank_transactions
    post 'imports/create'
  end
  resources :uncategorized_bank_transactions, only: [:index]

  get 'dashboard', to: 'dashboard#index'

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#pricing'
  get 'features', to: 'pages#features'
  get 'howto', to: 'pages#howto'

  devise_for :users
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :start_balance

  has_many :bank_transactions
  has_many :categories, through: :bank_transactions

  def balance_before_date(date)
    start_balance + bank_transactions.where('date < ?', date).sum(:amount)
  end

  def last_transaction_date
    bank_transactions.order(date: :desc).first.try(:date) || Time.zone.now
  end

  def last_balance
    start_balance + total_transaction_amount
  end

  def last_balance=(new_balance)
    new_balance = new_balance.to_s.gsub(",", "")
    self.start_balance = (BigDecimal(new_balance) - total_transaction_amount)
  end

  def total_transaction_amount
    bank_transactions.sum(:amount)
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  include BankTransactionsCumulativeSums
  include BankTransactionsByCategory
  include BankTransactionsDirectionals
  include DatesPageableByTimespan
  layout 'dashboard'
  before_action :authenticate_user!
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  before_action :authorize_bank_account, only: [:show, :edit, :update, :destroy]
  before_action :set_bank_account_last_date, only: [:show, :edit]

  def show
    dates = @bank_account.bank_transactions.get_sorted_dates
    @max_page = get_max_page(dates)
    dates = get_dates_for_timespan_page(dates)
    unordered_bank_transactions = @bank_account.bank_transactions.includes(:category)
                                        .for_date_range(dates.first, dates.last)

    @bank_account_sums = {
      name: @bank_account.name,
      data: calculate_cumulative_sums_by_day(
        bank_transactions: unordered_bank_transactions.order(date: :asc),
        start_balance: @bank_account.balance_before_date(dates.first)),
      }

    @bank_transactions_by_category = sum_by_category(
      bank_transactions: unordered_bank_transactions
    )

    @bank_transaction_directionals = sum_by_direction(
      bank_transactions: unordered_bank_transactions
    )

    @bank_transactions = unordered_bank_transactions.order(date: :desc)
  end

  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = current_user.bank_accounts.build(bank_account_params)

    if @bank_account.save
      redirect_to bank_account_path(@bank_account), notice: 'Account was successfully created.'
    end
  end

  def edit
  end

  def update
    if @bank_account.update(bank_account_params)
      redirect_to bank_account_path(@bank_account), notice: 'Account was successfully updated.'
    end
  end

  def destroy
    @bank_account.destroy
    redirect_to dashboard_path, notice: 'Account was successfully destroyed.'
  end

  private

  def set_bank_account
    @bank_account = BankAccount.find(params[:id])
  end

  def authorize_bank_account
    authorize @bank_account
  end

  def set_bank_account_last_date
    @last_balance_date = @bank_account.last_transaction_date
  end

  def bank_account_params
    params.require(:bank_account).permit(:user_id, :name, :bank_number, :last_balance)
  end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
  def get_sidebar_bank_accounts
    policy_scope(BankAccount).order(name: :asc)
  end

  def get_sidebar_categories
    policy_scope(Category).order(name: :asc)
  end

  def area_chart_helper(values, options={})
    values = [values] unless values.is_a? Array

    defaults = default_chart_options
    defaults[:stacked] = true
    options = defaults.merge(options)

    area_chart values, options
  end

  def line_chart_helper(values, options={})
    values = [values] unless values.is_a? Array
    defaults = default_chart_options
    defaults[:points] = true
    options = defaults.merge(options)

    line_chart values, options
  end

  def donut_chart_helper(values, options={})
    values = [values] unless values.is_a? Array
    defaults = default_chart_options
    defaults[:donut] = true
    options = defaults.merge(options)

    pie_chart values, options
  end

  def column_chart_helper(values, options={})
    values = [values] unless values.is_a? Array
    defaults = default_chart_options
    defaults[:library][:scales] = {
      yAxes: [{
        ticks: {
          beginAtZero: true,
        }
      }]
    }
    options = defaults.merge(options)

    column_chart values, options
  end

  def active? path
    "active" if current_page? path
  end

  def currency_color_class(amount)
    amount < 0 ? 'currency-negative' : 'currency-positive'
  end

  def category_link_helper(category)
    return link_to category.name, category if category
    '---'
  end

  def timespan_text(timespan)
    case timespan
    when :all
      'All time'
    else
      timespan.to_s.titleize + 'ly'
    end
  end

  def get_nonactive_timespans(active_timespan)
    timespans = [:all, :year, :month, :fortnight, :week]
    timespans.select { |t| t != active_timespan }
  end

  private

    def default_chart_options
      {
        defer: false,
        points: false,
        prefix: '$',
        thousands: ',',
        animation: true,
        messages: {empty: "No data"},
        library:
        {
          animation: {
            easing: 'easeOutQuart'
          },
        }
      }
    end
end

app/views/bank_accounts/_form.html.erb
<%= form_with model: @bank_account do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% @bank_account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label "Balance at #{@last_balance_date}" %>
    <%= f.text_field :last_balance %>
  </div>
  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/bank_accounts/create.js.erb
$("form").replaceWith("<%= j render "form" %>");

app/views/bank_accounts/edit.html.erb
<%= render 'form' %>
<div>
  <%= link_to 'Delete Account', @bank_account, method: :delete, id: 'delete_bank_account' %>
</div>

app/views/bank_accounts/new.html.erb
<%= render 'form' %>

app/views/bank_accounts/show.html.erb
<%= render partial: 'shared/dashboard_titlebar',
            locals: {
              name: @bank_account.name,
              record: @bank_account,
              edit_path: edit_bank_account_path(@bank_account),
              edit_id: 'edit_bank_account' }%>
<h2>Balance</h2>
<%= area_chart_helper @bank_account_sums, legend: false %>
<hr>
<%= render 'shared/dashboard_chart_incoming_outgoing' %>
<%= render 'shared/dashboard_chart_category_breakdown' %>
<a name="transactions">
  <h2 class='pt-5'>
    Transactions
    <span class="upload-icon" data-feather="upload" data-toggle="modal" data-target="#uploadModal"></span>
  </h2>
</a>
<div id="uploadModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Upload Transactions QIF File</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_tag(bank_account_imports_create_path(@bank_account), multipart: true) do %>
          <div class="form-group">
            Select file: <%= file_field_tag :file, accept: '.qif', class: 'form-control' %>
            <%= submit_tag 'Import', class: 'btn btn-info btn-block'  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'shared/dashboard_transactions',
           locals: {
             show_category: true
            }
%>

app/views/bank_accounts/update.js.erb
$("form").replaceWith("<%= j render "form" %>");